# Generated by Django 4.0 on 2024-04-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='quests_in_proress',
        ),
        migrations.AddField(
            model_name='customuser',
            name='quests_in_prgoress',
            field=models.ManyToManyField(related_name='quests_in_progress', through='api.UserQuestProgress', to='api.Quest'),
        ),
    ]
