# Generated by Django 4.0 on 2024-04-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_customuser_quests_in_proress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='quests_in_prgoress',
            new_name='quests_in_progress',
        ),
    ]
